[2024-05-15T02:59:03.118+0800] {processor.py:161} INFO - Started process (PID=65373) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T02:59:03.120+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T02:59:03.122+0800] {logging_mixin.py:188} INFO - [2024-05-15T02:59:03.122+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T02:59:03.126+0800] {logging_mixin.py:188} INFO - [2024-05-15T02:59:03.126+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T02:59:03.127+0800] {logging_mixin.py:188} INFO - [2024-05-15T02:59:03.126+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T02:59:03.127+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T02:59:03.141+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.035 seconds
[2024-05-15T03:00:04.827+0800] {processor.py:161} INFO - Started process (PID=66485) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:00:04.837+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:00:04.839+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:00:04.839+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:00:04.842+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:00:04.841+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:00:04.842+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:00:04.842+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:00:04.842+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:00:04.854+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.032 seconds
[2024-05-15T03:14:21.304+0800] {processor.py:161} INFO - Started process (PID=74846) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:14:21.366+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:14:21.369+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:14:21.368+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:14:21.374+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:14:21.373+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:14:21.374+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:14:21.374+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:14:21.375+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:14:21.390+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-05-15T03:15:23.618+0800] {processor.py:161} INFO - Started process (PID=75652) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:15:23.679+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:15:23.681+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:15:23.680+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:15:23.683+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:15:23.682+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:15:23.683+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:15:23.683+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:15:23.683+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:15:23.690+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
[2024-05-15T03:16:26.295+0800] {processor.py:161} INFO - Started process (PID=76409) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:16:26.306+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:16:26.307+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:16:26.307+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:16:26.309+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:16:26.309+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:16:26.309+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:16:26.309+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:16:26.309+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:16:26.316+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-05-15T03:17:28.791+0800] {processor.py:161} INFO - Started process (PID=77362) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:17:28.853+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:17:28.855+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:17:28.854+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:17:28.859+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:17:28.858+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:17:28.859+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:17:28.859+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:17:28.859+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:17:28.870+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-05-15T03:18:25.475+0800] {processor.py:161} INFO - Started process (PID=78175) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:18:25.475+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:18:25.476+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:18:25.476+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:18:25.479+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:18:25.479+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:18:25.479+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:18:25.479+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:18:25.479+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:18:25.489+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.020 seconds
[2024-05-15T03:19:16.549+0800] {processor.py:161} INFO - Started process (PID=78950) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:19:16.551+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:19:16.553+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:19:16.552+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:19:16.556+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:19:16.556+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:19:16.556+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:19:16.556+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:19:16.557+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:19:16.567+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.029 seconds
[2024-05-15T03:20:07.512+0800] {processor.py:161} INFO - Started process (PID=79687) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:20:07.566+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:20:07.571+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:20:07.570+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:20:07.586+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:20:07.584+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:20:07.587+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:20:07.587+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:20:07.588+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:20:07.607+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-05-15T03:21:00.527+0800] {processor.py:161} INFO - Started process (PID=80409) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:21:00.588+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:21:00.593+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:21:00.592+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:21:00.604+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:21:00.602+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:21:00.606+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:21:00.605+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:21:00.607+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:21:00.630+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2024-05-15T03:21:52.835+0800] {processor.py:161} INFO - Started process (PID=81175) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:21:52.845+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:21:52.847+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:21:52.847+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:21:52.850+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:21:52.849+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:21:52.850+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:21:52.850+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:21:52.850+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:21:52.858+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.030 seconds
[2024-05-15T03:22:45.135+0800] {processor.py:161} INFO - Started process (PID=81912) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:22:45.197+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:22:45.202+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:22:45.200+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:22:45.211+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:22:45.210+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:22:45.212+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:22:45.211+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:22:45.212+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:22:45.234+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.103 seconds
[2024-05-15T03:23:39.564+0800] {processor.py:161} INFO - Started process (PID=82433) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:23:39.626+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:23:39.631+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:23:39.629+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:23:39.640+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:23:39.638+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:23:39.641+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:23:39.640+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:23:39.642+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:23:39.664+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2024-05-15T03:24:34.117+0800] {processor.py:161} INFO - Started process (PID=82928) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:24:34.178+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:24:34.180+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:24:34.179+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:24:34.182+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:24:34.182+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:24:34.182+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:24:34.182+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:24:34.182+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:24:34.190+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
[2024-05-15T03:25:29.682+0800] {processor.py:161} INFO - Started process (PID=83401) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:25:29.742+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:25:29.745+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:25:29.745+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:25:29.751+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:25:29.750+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:25:29.751+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:25:29.751+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:25:29.752+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:25:29.769+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.092 seconds
[2024-05-15T03:26:21.560+0800] {processor.py:161} INFO - Started process (PID=83792) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:26:21.623+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:26:21.628+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:26:21.627+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:26:21.637+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:26:21.636+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:26:21.638+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:26:21.638+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:26:21.639+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:26:21.661+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.118 seconds
[2024-05-15T03:27:16.351+0800] {processor.py:161} INFO - Started process (PID=84580) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:27:16.414+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:27:16.418+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:27:16.417+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:27:16.429+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:27:16.427+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:27:16.429+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:27:16.429+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:27:16.430+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:27:16.451+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.119 seconds
[2024-05-15T03:28:08.099+0800] {processor.py:161} INFO - Started process (PID=84975) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:28:08.160+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:28:08.164+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:28:08.163+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:28:08.174+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:28:08.172+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:28:08.175+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:28:08.174+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:28:08.175+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:28:08.200+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
[2024-05-15T03:28:55.933+0800] {processor.py:161} INFO - Started process (PID=85391) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:28:55.997+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:28:56.000+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:28:56.000+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:28:56.006+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:28:56.005+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:28:56.006+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:28:56.006+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:28:56.006+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:28:56.017+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.089 seconds
[2024-05-15T03:29:46.324+0800] {processor.py:161} INFO - Started process (PID=85860) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:29:46.359+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:29:46.363+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:29:46.362+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:29:46.372+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:29:46.371+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:29:46.373+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:29:46.372+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:29:46.374+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:29:46.397+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2024-05-15T03:30:36.365+0800] {processor.py:161} INFO - Started process (PID=86306) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:30:36.389+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:30:36.390+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:30:36.390+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:30:36.392+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:30:36.392+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:30:36.393+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:30:36.393+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:30:36.393+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:30:36.400+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.043 seconds
[2024-05-15T03:31:28.677+0800] {processor.py:161} INFO - Started process (PID=86744) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:31:28.739+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:31:28.747+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:31:28.745+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:31:28.758+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:31:28.757+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:31:28.760+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:31:28.759+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:31:28.760+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:31:28.779+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.112 seconds
[2024-05-15T03:32:19.695+0800] {processor.py:161} INFO - Started process (PID=87144) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:32:19.757+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:32:19.762+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:32:19.761+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:32:19.769+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:32:19.768+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:32:19.770+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:32:19.770+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:32:19.770+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:32:19.785+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.100 seconds
[2024-05-15T03:33:09.350+0800] {processor.py:161} INFO - Started process (PID=87595) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:33:09.411+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:33:09.416+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:33:09.415+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:33:09.422+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:33:09.421+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:33:09.423+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:33:09.423+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:33:09.424+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:33:09.438+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.092 seconds
[2024-05-15T03:34:06.410+0800] {processor.py:161} INFO - Started process (PID=88141) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:34:06.413+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:34:06.414+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:34:06.414+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:34:06.416+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:34:06.416+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:34:06.417+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:34:06.417+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:34:06.417+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:34:06.429+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-05-15T03:34:53.506+0800] {processor.py:161} INFO - Started process (PID=88569) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:34:53.567+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:34:53.569+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:34:53.569+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:34:53.571+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:34:53.571+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:34:53.572+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:34:53.571+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:34:53.572+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:34:53.579+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.077 seconds
[2024-05-15T03:35:43.315+0800] {processor.py:161} INFO - Started process (PID=89005) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:35:43.375+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:35:43.377+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:35:43.377+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:35:43.380+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:35:43.380+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:35:43.381+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:35:43.381+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:35:43.381+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:35:43.391+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2024-05-15T03:36:31.620+0800] {processor.py:161} INFO - Started process (PID=89510) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:36:31.681+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:36:31.683+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:36:31.682+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:36:31.685+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:36:31.685+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:36:31.686+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:36:31.686+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:36:31.686+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:36:31.695+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2024-05-15T03:37:21.229+0800] {processor.py:161} INFO - Started process (PID=89896) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:37:21.290+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:37:21.291+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:37:21.291+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:37:21.293+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:37:21.293+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:37:21.293+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:37:21.293+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:37:21.294+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:37:21.301+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2024-05-15T03:38:11.895+0800] {processor.py:161} INFO - Started process (PID=90379) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:38:11.956+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:38:11.958+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:38:11.957+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:38:11.962+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:38:11.961+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:38:11.962+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:38:11.962+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:38:11.962+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:38:11.975+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2024-05-15T03:39:01.187+0800] {processor.py:161} INFO - Started process (PID=91006) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:39:01.249+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:39:01.252+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:39:01.251+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:39:01.257+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:39:01.256+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:39:01.257+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:39:01.257+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:39:01.257+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:39:01.268+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.089 seconds
[2024-05-15T03:40:06.318+0800] {processor.py:161} INFO - Started process (PID=92782) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:40:06.320+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:40:06.322+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:40:06.322+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:40:06.326+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:40:06.326+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:40:06.327+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:40:06.326+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:40:06.327+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:40:06.339+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.031 seconds
[2024-05-15T03:41:04.444+0800] {processor.py:161} INFO - Started process (PID=93618) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:41:04.505+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:41:04.508+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:41:04.507+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:41:04.511+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:41:04.510+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:41:04.511+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:41:04.511+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:41:04.511+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:41:04.518+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.084 seconds
[2024-05-15T03:41:58.591+0800] {processor.py:161} INFO - Started process (PID=94399) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:41:58.653+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:41:58.657+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:41:58.656+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:41:58.667+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:41:58.665+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:41:58.668+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:41:58.667+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:41:58.669+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:41:58.689+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2024-05-15T03:42:52.413+0800] {processor.py:161} INFO - Started process (PID=95133) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:42:52.474+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:42:52.480+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:42:52.478+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:42:52.489+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:42:52.487+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:42:52.490+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:42:52.489+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:42:52.490+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:42:52.516+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.109 seconds
[2024-05-15T03:43:46.034+0800] {processor.py:161} INFO - Started process (PID=95902) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:43:46.095+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:43:46.102+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:43:46.100+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:43:46.113+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:43:46.112+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:43:46.114+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:43:46.114+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:43:46.115+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:43:46.133+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2024-05-15T03:44:42.837+0800] {processor.py:161} INFO - Started process (PID=96738) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:44:42.899+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:44:42.902+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:44:42.901+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:44:42.907+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:44:42.907+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:44:42.908+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:44:42.907+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:44:42.908+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:44:42.920+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.097 seconds
[2024-05-15T03:45:38.858+0800] {processor.py:161} INFO - Started process (PID=97314) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:45:38.859+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:45:38.861+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:45:38.860+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:45:38.864+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:45:38.863+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:45:38.864+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:45:38.864+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:45:38.864+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:45:38.873+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.021 seconds
[2024-05-15T03:46:45.297+0800] {processor.py:161} INFO - Started process (PID=98375) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:46:45.299+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:46:45.301+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:46:45.301+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:46:45.304+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:46:45.304+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:46:45.304+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:46:45.304+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:46:45.305+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:46:45.312+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.022 seconds
[2024-05-15T03:47:42.684+0800] {processor.py:161} INFO - Started process (PID=99177) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:47:42.694+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:47:42.696+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:47:42.695+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:47:42.699+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:47:42.699+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:47:42.699+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:47:42.699+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:47:42.699+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:47:42.706+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-05-15T03:48:29.930+0800] {processor.py:161} INFO - Started process (PID=99870) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:48:29.992+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:48:29.995+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:48:29.994+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:48:29.999+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:48:29.998+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:48:29.999+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:48:29.999+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:48:30.000+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:48:30.014+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.102 seconds
[2024-05-15T03:49:26.852+0800] {processor.py:161} INFO - Started process (PID=100727) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:49:26.888+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:49:26.890+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:49:26.890+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:49:26.894+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:49:26.894+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:49:26.895+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:49:26.895+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:49:26.895+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:49:26.911+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.066 seconds
[2024-05-15T03:50:22.874+0800] {processor.py:161} INFO - Started process (PID=101496) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:50:22.938+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:50:22.939+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:50:22.939+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:50:22.944+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:50:22.943+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:50:22.944+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:50:22.944+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:50:22.944+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:50:22.952+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.093 seconds
[2024-05-15T03:51:20.230+0800] {processor.py:161} INFO - Started process (PID=102355) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:51:20.292+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:51:20.298+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:51:20.297+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:51:20.308+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:51:20.307+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:51:20.310+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:51:20.309+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:51:20.311+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:51:20.332+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.115 seconds
[2024-05-15T03:52:10.877+0800] {processor.py:161} INFO - Started process (PID=102808) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:52:10.940+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:52:10.942+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:52:10.941+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:52:10.944+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:52:10.943+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:52:10.944+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:52:10.944+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:52:10.944+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:52:10.952+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.079 seconds
[2024-05-15T03:52:58.920+0800] {processor.py:161} INFO - Started process (PID=103339) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:52:58.982+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:52:58.988+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:52:58.986+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:52:58.995+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:52:58.994+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:52:58.996+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:52:58.995+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:52:58.996+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:52:59.011+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
[2024-05-15T03:53:54.867+0800] {processor.py:161} INFO - Started process (PID=104015) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:53:54.928+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:53:54.934+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:53:54.932+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:53:54.943+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:53:54.942+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:53:54.945+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:53:54.944+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:53:54.946+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:53:54.964+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
[2024-05-15T03:54:51.687+0800] {processor.py:161} INFO - Started process (PID=104759) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:54:51.749+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:54:51.754+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:54:51.753+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:54:51.762+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:54:51.761+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:54:51.763+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:54:51.763+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:54:51.764+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:54:51.788+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.107 seconds
[2024-05-15T03:55:45.483+0800] {processor.py:161} INFO - Started process (PID=105431) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:55:45.485+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:55:45.488+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:55:45.487+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:55:45.493+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:55:45.492+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:55:45.493+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:55:45.493+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:55:45.493+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:55:45.505+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.038 seconds
[2024-05-15T03:56:34.477+0800] {processor.py:161} INFO - Started process (PID=105874) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:56:34.538+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:56:34.543+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:56:34.542+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:56:34.552+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:56:34.551+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:56:34.553+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:56:34.553+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:56:34.554+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:56:34.577+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.104 seconds
[2024-05-15T03:57:24.583+0800] {processor.py:161} INFO - Started process (PID=106374) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:57:24.644+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:57:24.648+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:57:24.647+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:57:24.655+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:57:24.654+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:57:24.656+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:57:24.656+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:57:24.657+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:57:24.676+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.098 seconds
[2024-05-15T03:58:08.778+0800] {processor.py:161} INFO - Started process (PID=106749) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:58:08.841+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:58:08.842+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:58:08.842+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:58:08.844+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:58:08.844+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:58:08.844+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:58:08.844+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:58:08.845+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:58:08.852+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.080 seconds
[2024-05-15T03:58:57.158+0800] {processor.py:161} INFO - Started process (PID=107281) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:58:57.219+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:58:57.220+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:58:57.220+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:58:57.222+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:58:57.222+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:58:57.223+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:58:57.222+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:58:57.223+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:58:57.237+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2024-05-15T03:59:47.580+0800] {processor.py:161} INFO - Started process (PID=107738) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:59:47.641+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T03:59:47.642+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:59:47.642+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:59:47.646+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:59:47.645+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T03:59:47.646+0800] {logging_mixin.py:188} INFO - [2024-05-15T03:59:47.646+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T03:59:47.646+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T03:59:47.654+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.078 seconds
[2024-05-15T04:00:34.516+0800] {processor.py:161} INFO - Started process (PID=108150) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:00:34.535+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:00:34.536+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:00:34.536+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:00:34.538+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:00:34.538+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:00:34.539+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:00:34.539+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:00:34.539+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:00:34.548+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.041 seconds
[2024-05-15T04:01:23.719+0800] {processor.py:161} INFO - Started process (PID=108560) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:01:23.780+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:01:23.785+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:01:23.784+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:01:23.787+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:01:23.787+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:01:23.788+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:01:23.787+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:01:23.788+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:01:23.795+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.081 seconds
[2024-05-15T04:02:11.937+0800] {processor.py:161} INFO - Started process (PID=108973) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:02:11.998+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:02:12.000+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:02:11.999+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:02:12.003+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:02:12.003+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:02:12.003+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:02:12.003+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:02:12.004+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:02:12.017+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.085 seconds
[2024-05-15T04:03:04.561+0800] {processor.py:161} INFO - Started process (PID=109539) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:03:04.622+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:03:04.625+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:03:04.624+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:03:04.628+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:03:04.628+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:03:04.629+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:03:04.628+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:03:04.629+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:03:04.638+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.082 seconds
[2024-05-15T04:04:13.412+0800] {processor.py:161} INFO - Started process (PID=110732) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:04:13.474+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:04:13.478+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:04:13.477+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:04:13.489+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:04:13.487+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:04:13.490+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:04:13.489+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:04:13.490+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:04:13.512+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
[2024-05-15T04:05:11.745+0800] {processor.py:161} INFO - Started process (PID=111551) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:05:11.746+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:05:11.748+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:05:11.748+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:05:11.750+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:05:11.750+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:05:11.751+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:05:11.751+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:05:11.751+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:05:11.759+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-05-15T04:06:05.439+0800] {processor.py:161} INFO - Started process (PID=112314) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:06:05.502+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:06:05.507+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:06:05.506+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:06:05.517+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:06:05.516+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:06:05.518+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:06:05.518+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:06:05.519+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:06:05.543+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.116 seconds
[2024-05-15T04:07:02.974+0800] {processor.py:161} INFO - Started process (PID=113132) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:07:02.976+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:07:02.977+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:07:02.977+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:07:02.981+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:07:02.980+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:07:02.982+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:07:02.982+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:07:02.982+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:07:02.992+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.028 seconds
[2024-05-15T04:07:58.115+0800] {processor.py:161} INFO - Started process (PID=113764) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:07:58.116+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:07:58.119+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:07:58.118+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:07:58.122+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:07:58.121+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:07:58.122+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:07:58.122+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:07:58.122+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:07:58.130+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.019 seconds
[2024-05-15T04:08:56.877+0800] {processor.py:161} INFO - Started process (PID=114646) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:08:56.880+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:08:56.882+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:08:56.881+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:08:56.886+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:08:56.885+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:08:56.886+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:08:56.886+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:08:56.887+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:08:56.896+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.027 seconds
[2024-05-15T04:09:53.435+0800] {processor.py:161} INFO - Started process (PID=115495) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:09:53.497+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:09:53.502+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:09:53.500+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:09:53.507+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:09:53.506+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:09:53.507+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:09:53.507+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:09:53.508+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:09:53.522+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.106 seconds
[2024-05-15T04:10:46.328+0800] {processor.py:161} INFO - Started process (PID=116276) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:10:46.330+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:10:46.331+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:10:46.331+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:10:46.334+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:10:46.334+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:10:46.335+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:10:46.334+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:10:46.335+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:10:46.345+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.026 seconds
[2024-05-15T04:11:40.710+0800] {processor.py:161} INFO - Started process (PID=117037) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:11:40.771+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:11:40.777+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:11:40.776+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:11:40.787+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:11:40.785+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:11:40.788+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:11:40.788+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:11:40.789+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:11:40.813+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.110 seconds
[2024-05-15T04:12:43.381+0800] {processor.py:161} INFO - Started process (PID=117921) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:12:43.443+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:12:43.449+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:12:43.447+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:12:43.458+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:12:43.456+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:12:43.459+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:12:43.458+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:12:43.459+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:12:43.477+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.105 seconds
[2024-05-15T04:13:39.338+0800] {processor.py:161} INFO - Started process (PID=118732) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:13:39.339+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:13:39.340+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:13:39.340+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:13:39.343+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:13:39.343+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:13:39.344+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:13:39.344+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:13:39.344+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:13:39.351+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.018 seconds
[2024-05-15T04:14:36.069+0800] {processor.py:161} INFO - Started process (PID=119527) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:14:36.073+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:14:36.077+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:14:36.076+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:14:36.082+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:14:36.081+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:14:36.082+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:14:36.082+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:14:36.083+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:14:36.095+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.045 seconds
[2024-05-15T04:15:30.471+0800] {processor.py:161} INFO - Started process (PID=120071) to work on /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:15:30.533+0800] {processor.py:830} INFO - Processing file /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py for tasks to queue
[2024-05-15T04:15:30.537+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:15:30.536+0800] {dagbag.py:545} INFO - Filling up the DagBag from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:15:30.543+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:15:30.542+0800] {example_local_kubernetes_executor.py:40} WARNING - Could not import DAGs in example_local_kubernetes_executor.py
Traceback (most recent call last):
  File "/home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py", line 38, in <module>
    from kubernetes.client import models as k8s
ModuleNotFoundError: No module named 'kubernetes'
[2024-05-15T04:15:30.543+0800] {logging_mixin.py:188} INFO - [2024-05-15T04:15:30.543+0800] {example_local_kubernetes_executor.py:41} WARNING - Install Kubernetes dependencies with: pip install apache-airflow[cncf.kubernetes]
[2024-05-15T04:15:30.544+0800] {processor.py:842} WARNING - No viable dags retrieved from /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py
[2024-05-15T04:15:30.557+0800] {processor.py:183} INFO - Processing /home/jithish/Documents/dag-dag-dag/.venv/lib/python3.10/site-packages/airflow/example_dags/example_local_kubernetes_executor.py took 0.090 seconds
