[2024-05-15T04:08:41.090+0800] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2024-05-15T04:08:41.113+0800] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: census_data_pipeline.process_data manual__2024-05-14T20:03:27.189773+00:00 [queued]>
[2024-05-15T04:08:41.120+0800] {taskinstance.py:2076} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: census_data_pipeline.process_data manual__2024-05-14T20:03:27.189773+00:00 [queued]>
[2024-05-15T04:08:41.120+0800] {taskinstance.py:2306} INFO - Starting attempt 2 of 2
[2024-05-15T04:08:41.133+0800] {taskinstance.py:2330} INFO - Executing <Task(PythonOperator): process_data> on 2024-05-14 20:03:27.189773+00:00
[2024-05-15T04:08:41.137+0800] {standard_task_runner.py:63} INFO - Started process 114392 to run task
[2024-05-15T04:08:41.140+0800] {standard_task_runner.py:90} INFO - Running: ['airflow', 'tasks', 'run', 'census_data_pipeline', 'process_data', 'manual__2024-05-14T20:03:27.189773+00:00', '--job-id', '19', '--raw', '--subdir', 'DAGS_FOLDER/my_dag.py', '--cfg-path', '/tmp/tmprjeigknh']
[2024-05-15T04:08:41.141+0800] {standard_task_runner.py:91} INFO - Job 19: Subtask process_data
[2024-05-15T04:08:41.166+0800] {task_command.py:426} INFO - Running <TaskInstance: census_data_pipeline.process_data manual__2024-05-14T20:03:27.189773+00:00 [running]> on host jithish-HP-ZBook-17-G5
[2024-05-15T04:08:41.212+0800] {taskinstance.py:2648} INFO - Exporting env vars: AIRFLOW_CTX_DAG_EMAIL='example@example.com' AIRFLOW_CTX_DAG_OWNER='airflow' AIRFLOW_CTX_DAG_ID='census_data_pipeline' AIRFLOW_CTX_TASK_ID='process_data' AIRFLOW_CTX_EXECUTION_DATE='2024-05-14T20:03:27.189773+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2024-05-14T20:03:27.189773+00:00'
[2024-05-15T04:08:41.213+0800] {taskinstance.py:430} INFO - ::endgroup::
[2024-05-15T04:08:41.222+0800] {logging_mixin.py:188} WARNING - /home/jithish/Documents/dag-dag-dag/airflow/dags/my_dag.py:36 FutureWarning: DataFrame.fillna with 'method' is deprecated and will raise in a future version. Use obj.ffill() or obj.bfill() instead.
[2024-05-15T04:08:41.226+0800] {python.py:237} INFO - Done. Returned value was: None
[2024-05-15T04:08:41.226+0800] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2024-05-15T04:08:41.229+0800] {taskinstance.py:1206} INFO - Marking task as SUCCESS. dag_id=census_data_pipeline, task_id=process_data, run_id=manual__2024-05-14T20:03:27.189773+00:00, execution_date=20240514T200327, start_date=20240514T200841, end_date=20240514T200841
[2024-05-15T04:08:41.272+0800] {local_task_job_runner.py:240} INFO - Task exited with return code 0
[2024-05-15T04:08:41.314+0800] {taskinstance.py:3498} INFO - 1 downstream tasks scheduled from follow-on schedule check
[2024-05-15T04:08:41.317+0800] {local_task_job_runner.py:222} INFO - ::endgroup::
